### ISSUE TITLE
config words : && instead of &

### ISSUE THREAD

**Issue by fenugrec** [diegoherranz/sdcc-examples#1]
I think '&' was intended (bitwise & instead of logical &&) for the config word settings, such as in

```
__code uint16_t __at (_CONFIG1) __configword = _INTRC_OSC_NOCLKOUT && _WDTE_OFF && _LVP_OFF;
```

https://github.com/diegoherranz/sdcc-examples/blob/master/pic14/2.seven_seg/seven_seg.c#L11
and probably others too !

**Comment by diegoherranz** [comment]
I did even write the Configuration Bits section of the [SDCC manual](http://sdcc.sourceforge.net/doc/sdccman.pdf) (correctly), but I made a typo here.

Thanks for reporting!
